/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xyz_jvm_example_jni_JavaThread */

#ifndef _Included_org_xyz_jvm_example_jni_JavaThread
#define _Included_org_xyz_jvm_example_jni_JavaThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xyz_jvm_example_jni_JavaThread
 * Method:    start0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_xyz_jvm_example_jni_JavaThread_start0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
