/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "../../include/jni/Handle.h"
/* Header for class org_xyz_jvm_jdk_classes_sun_misc_Unsafe */

#ifndef _Included_org_xyz_jvm_jdk_classes_sun_misc_Unsafe
#define _Included_org_xyz_jvm_jdk_classes_sun_misc_Unsafe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xyz_jvm_jdk_classes_sun_misc_Unsafe
 * Method:    allocateMemory
 * Signature: (J)J
 */
JNIEXPORT jobject JNICALL Java_org_xyz_jvm_jdk_classes_sun_misc_Unsafe_allocateMemory
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
