/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "../../include/jni/Handle.h"
#include "../../share/vm/oops/instanceKlass.hpp"
/* Header for class org_xyz_jvm_jdk_classes_sun_misc_Unsafe */

#ifndef _Included_org_xyz_jvm_jdk_classes_sun_misc_Unsafe
#define _Included_org_xyz_jvm_jdk_classes_sun_misc_Unsafe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xyz_jvm_jdk_classes_sun_misc_Unsafe
 * Method:    allocateMemory
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_xyz_jvm_jdk_classes_sun_misc_Unsafe_allocateMemory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_xyz_jvm_jdk_classes_sun_misc_Unsafe
 * Method:    allocateObject
 * Signature: ()Lorg/xyz/jvm/jdk/classes/Handle;
 */
JNIEXPORT jobject JNICALL Java_org_xyz_jvm_jdk_classes_sun_misc_Unsafe_allocateObject
        (JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
