/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xyz_jvm_jdk_Threads */

#ifndef _Included_org_xyz_jvm_jdk_Threads
#define _Included_org_xyz_jvm_jdk_Threads
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xyz_jvm_jdk_Threads
 * Method:    createVm
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_xyz_jvm_jdk_Threads_createVm
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
