/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xyz_jvm_jdk_classes_sun_misc_AppClassLoader */

#ifndef _Included_org_xyz_jvm_jdk_classes_sun_misc_AppClassLoader
#define _Included_org_xyz_jvm_jdk_classes_sun_misc_AppClassLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xyz_jvm_jdk_classes_sun_misc_AppClassLoader
 * Method:    loadKlass
 * Signature: (Ljava/lang/String;)Lorg/xyz/jvm/jdk/classes/Handle;
 */
JNIEXPORT jobject JNICALL Java_org_xyz_jvm_jdk_classes_sun_misc_AppClassLoader_loadKlass
        (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif